"""changed the foregin key to be oncascade

Revision ID: 0099f144e76a
Revises: 994c65b1977b
Create Date: 2025-08-16 15:58:06.458784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0099f144e76a'
down_revision: Union[str, None] = '994c65b1977b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('indexing_results_job_id_fkey'), 'indexing_results', type_='foreignkey')
    op.create_foreign_key(None, 'indexing_results', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indexing_results', type_='foreignkey')
    op.create_foreign_key(op.f('indexing_results_job_id_fkey'), 'indexing_results', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
