"""Add relationships and cascade rules for Product and ImageProduct

Revision ID: 1106fbf69687
Revises: 418fb2e860c4
Create Date: 2025-08-16 14:45:01.899972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1106fbf69687'
down_revision: Union[str, None] = '418fb2e860c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_images_image_id_fkey'), 'product_images', type_='foreignkey')
    op.drop_constraint(op.f('product_images_product_id_fkey'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_images', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_images_product_id_fkey'), 'product_images', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_images_image_id_fkey'), 'product_images', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
