"""image migration created

Revision ID: 33a6a4caa63f
Revises: dc5b0a5c0c76
Create Date: 2025-07-05 21:12:31.155744

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from backend.app.models.image import StatusEnum

# revision identifiers, used by Alembic.
revision: str = '33a6a4caa63f'
down_revision: Union[str, None] = 'dc5b0a5c0c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
    
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
        sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('label', sa.JSON(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('processing_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('original_id', sa.Uuid(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        # Use String with CHECK constraint instead of native ENUM
        sa.Column('status', sa.String(20), nullable=False),
        sa.CheckConstraint(
            "status IN ('uploaded', 'queued', 'cropping', 'analyzing', 'cropped', 'labelled', 'storing', 'stored', 'complete', 'failed')",
            name='check_status_enum'
        ),
        sa.ForeignKeyConstraint(['original_id'], ['image.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###