"""Add query and query_similar_product tables

Revision ID: 39ba617e4dee
Revises: 33a6a4caa63f
Create Date: 2025-07-25 19:18:09.580267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39ba617e4dee'
down_revision: Union[str, None] = '33a6a4caa63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('input_image_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['input_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_similar_product',
    sa.Column('image_query_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_query_id'], ['query_image.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('image_query_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_similar_product')
    op.drop_table('query_image')
    # ### end Alembic commands ###
