"""A changed image table in the label column type to accept json format

Revision ID: 4153a5dd612b
Revises: 33a6a4caa63f
Create Date: 2025-07-19 21:56:07.359935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4153a5dd612b'
down_revision: Union[str, None] = '33a6a4caa63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('processing_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
# We are replacing the autogenerated command with raw SQL to include the USING clause.
    op.execute("ALTER TABLE image ALTER COLUMN label TYPE JSON USING label::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE image ALTER COLUMN label TYPE VARCHAR")
    op.drop_column('image', 'processing_details')
    # ### end Alembic commands ###
