"""create delete on cascade for original id

Revision ID: d6cc37ac7cb5
Revises: 1106fbf69687
Create Date: 2025-08-16 15:31:09.504927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6cc37ac7cb5'
down_revision: Union[str, None] = '1106fbf69687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_original_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'images', ['original_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_original_id_fkey'), 'images', 'images', ['original_id'], ['id'])
    # ### end Alembic commands ###
